// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/delete_url_service.go
//
// Generated by this command:
//
//	mockgen -source internal/service/delete_url_service.go -destination internal/pkg/mocks/mock_delete_url_service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/aleffnull/shortener/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteURLsService is a mock of DeleteURLsService interface.
type MockDeleteURLsService struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteURLsServiceMockRecorder
	isgomock struct{}
}

// MockDeleteURLsServiceMockRecorder is the mock recorder for MockDeleteURLsService.
type MockDeleteURLsServiceMockRecorder struct {
	mock *MockDeleteURLsService
}

// NewMockDeleteURLsService creates a new mock instance.
func NewMockDeleteURLsService(ctrl *gomock.Controller) *MockDeleteURLsService {
	mock := &MockDeleteURLsService{ctrl: ctrl}
	mock.recorder = &MockDeleteURLsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteURLsService) EXPECT() *MockDeleteURLsServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleteURLsService) Delete(request *domain.DeleteURLsRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", request)
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleteURLsServiceMockRecorder) Delete(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleteURLsService)(nil).Delete), request)
}

// Init mocks base method.
func (m *MockDeleteURLsService) Init() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Init")
}

// Init indicates an expected call of Init.
func (mr *MockDeleteURLsServiceMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDeleteURLsService)(nil).Init))
}

// Shutdown mocks base method.
func (m *MockDeleteURLsService) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockDeleteURLsServiceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockDeleteURLsService)(nil).Shutdown))
}
