// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/store/store.go
//
// Generated by this command:
//
//	mockgen -source internal/pkg/store/store.go -destination internal/pkg/mocks/mock_store.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/aleffnull/shortener/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStoreManager is a mock of StoreManager interface.
type MockStoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockStoreManagerMockRecorder
	isgomock struct{}
}

// MockStoreManagerMockRecorder is the mock recorder for MockStoreManager.
type MockStoreManagerMockRecorder struct {
	mock *MockStoreManager
}

// NewMockStoreManager creates a new mock instance.
func NewMockStoreManager(ctrl *gomock.Controller) *MockStoreManager {
	mock := &MockStoreManager{ctrl: ctrl}
	mock.recorder = &MockStoreManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreManager) EXPECT() *MockStoreManagerMockRecorder {
	return m.recorder
}

// CheckAvailability mocks base method.
func (m *MockStoreManager) CheckAvailability(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailability", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailability indicates an expected call of CheckAvailability.
func (mr *MockStoreManagerMockRecorder) CheckAvailability(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailability", reflect.TypeOf((*MockStoreManager)(nil).CheckAvailability), arg0)
}

// Init mocks base method.
func (m *MockStoreManager) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockStoreManagerMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockStoreManager)(nil).Init))
}

// MockDataStore is a mock of DataStore interface.
type MockDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreMockRecorder
	isgomock struct{}
}

// MockDataStoreMockRecorder is the mock recorder for MockDataStore.
type MockDataStoreMockRecorder struct {
	mock *MockDataStore
}

// NewMockDataStore creates a new mock instance.
func NewMockDataStore(ctrl *gomock.Controller) *MockDataStore {
	mock := &MockDataStore{ctrl: ctrl}
	mock.recorder = &MockDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStore) EXPECT() *MockDataStoreMockRecorder {
	return m.recorder
}

// DeleteBatch mocks base method.
func (m *MockDataStore) DeleteBatch(arg0 context.Context, arg1 []string, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockDataStoreMockRecorder) DeleteBatch(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockDataStore)(nil).DeleteBatch), arg0, arg1, arg2)
}

// GetStatistics mocks base method.
func (m *MockDataStore) GetStatistics(arg0 context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockDataStoreMockRecorder) GetStatistics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockDataStore)(nil).GetStatistics), arg0)
}

// Load mocks base method.
func (m *MockDataStore) Load(arg0 context.Context, arg1 string) (*domain.URLItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1)
	ret0, _ := ret[0].(*domain.URLItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockDataStoreMockRecorder) Load(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockDataStore)(nil).Load), arg0, arg1)
}

// LoadAllByUserID mocks base method.
func (m *MockDataStore) LoadAllByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*domain.KeyOriginalURLItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAllByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.KeyOriginalURLItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAllByUserID indicates an expected call of LoadAllByUserID.
func (mr *MockDataStoreMockRecorder) LoadAllByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAllByUserID", reflect.TypeOf((*MockDataStore)(nil).LoadAllByUserID), arg0, arg1)
}

// Save mocks base method.
func (m *MockDataStore) Save(arg0 context.Context, arg1 string, arg2 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockDataStoreMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDataStore)(nil).Save), arg0, arg1, arg2)
}

// SaveBatch mocks base method.
func (m *MockDataStore) SaveBatch(arg0 context.Context, arg1 []*domain.BatchRequestItem, arg2 uuid.UUID) ([]*domain.BatchResponseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.BatchResponseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockDataStoreMockRecorder) SaveBatch(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockDataStore)(nil).SaveBatch), arg0, arg1, arg2)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CheckAvailability mocks base method.
func (m *MockStore) CheckAvailability(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailability", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailability indicates an expected call of CheckAvailability.
func (mr *MockStoreMockRecorder) CheckAvailability(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailability", reflect.TypeOf((*MockStore)(nil).CheckAvailability), arg0)
}

// DeleteBatch mocks base method.
func (m *MockStore) DeleteBatch(arg0 context.Context, arg1 []string, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockStoreMockRecorder) DeleteBatch(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockStore)(nil).DeleteBatch), arg0, arg1, arg2)
}

// GetStatistics mocks base method.
func (m *MockStore) GetStatistics(arg0 context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockStoreMockRecorder) GetStatistics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockStore)(nil).GetStatistics), arg0)
}

// Init mocks base method.
func (m *MockStore) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockStoreMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockStore)(nil).Init))
}

// Load mocks base method.
func (m *MockStore) Load(arg0 context.Context, arg1 string) (*domain.URLItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1)
	ret0, _ := ret[0].(*domain.URLItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockStoreMockRecorder) Load(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStore)(nil).Load), arg0, arg1)
}

// LoadAllByUserID mocks base method.
func (m *MockStore) LoadAllByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*domain.KeyOriginalURLItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAllByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.KeyOriginalURLItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAllByUserID indicates an expected call of LoadAllByUserID.
func (mr *MockStoreMockRecorder) LoadAllByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAllByUserID", reflect.TypeOf((*MockStore)(nil).LoadAllByUserID), arg0, arg1)
}

// Save mocks base method.
func (m *MockStore) Save(arg0 context.Context, arg1 string, arg2 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockStoreMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStore)(nil).Save), arg0, arg1, arg2)
}

// SaveBatch mocks base method.
func (m *MockStore) SaveBatch(arg0 context.Context, arg1 []*domain.BatchRequestItem, arg2 uuid.UUID) ([]*domain.BatchResponseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.BatchResponseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockStoreMockRecorder) SaveBatch(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockStore)(nil).SaveBatch), arg0, arg1, arg2)
}

// MockColdStore is a mock of ColdStore interface.
type MockColdStore struct {
	ctrl     *gomock.Controller
	recorder *MockColdStoreMockRecorder
	isgomock struct{}
}

// MockColdStoreMockRecorder is the mock recorder for MockColdStore.
type MockColdStoreMockRecorder struct {
	mock *MockColdStore
}

// NewMockColdStore creates a new mock instance.
func NewMockColdStore(ctrl *gomock.Controller) *MockColdStore {
	mock := &MockColdStore{ctrl: ctrl}
	mock.recorder = &MockColdStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColdStore) EXPECT() *MockColdStoreMockRecorder {
	return m.recorder
}

// LoadAll mocks base method.
func (m *MockColdStore) LoadAll() ([]*domain.ColdStoreEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll")
	ret0, _ := ret[0].([]*domain.ColdStoreEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockColdStoreMockRecorder) LoadAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockColdStore)(nil).LoadAll))
}

// Save mocks base method.
func (m *MockColdStore) Save(arg0 *domain.ColdStoreEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockColdStoreMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockColdStore)(nil).Save), arg0)
}
