// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/audit_service.go
//
// Generated by this command:
//
//	mockgen -source internal/service/audit_service.go -destination internal/pkg/mocks/mock_audit_service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/aleffnull/shortener/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// AuditEvent mocks base method.
func (m *MockAuditService) AuditEvent(event *domain.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AuditEvent", event)
}

// AuditEvent indicates an expected call of AuditEvent.
func (mr *MockAuditServiceMockRecorder) AuditEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditEvent", reflect.TypeOf((*MockAuditService)(nil).AuditEvent), event)
}

// Init mocks base method.
func (m *MockAuditService) Init() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Init")
}

// Init indicates an expected call of Init.
func (mr *MockAuditServiceMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAuditService)(nil).Init))
}

// Shutdown mocks base method.
func (m *MockAuditService) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockAuditServiceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockAuditService)(nil).Shutdown))
}
