// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/parameters/app_parameters.go
//
// Generated by this command:
//
//	mockgen -source internal/pkg/parameters/app_parameters.go -destination internal/pkg/mocks/mock_app_parameters.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppParameters is a mock of AppParameters interface.
type MockAppParameters struct {
	ctrl     *gomock.Controller
	recorder *MockAppParametersMockRecorder
	isgomock struct{}
}

// MockAppParametersMockRecorder is the mock recorder for MockAppParameters.
type MockAppParametersMockRecorder struct {
	mock *MockAppParameters
}

// NewMockAppParameters creates a new mock instance.
func NewMockAppParameters(ctrl *gomock.Controller) *MockAppParameters {
	mock := &MockAppParameters{ctrl: ctrl}
	mock.recorder = &MockAppParametersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppParameters) EXPECT() *MockAppParametersMockRecorder {
	return m.recorder
}

// GetJWTSingningKey mocks base method.
func (m *MockAppParameters) GetJWTSingningKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWTSingningKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJWTSingningKey indicates an expected call of GetJWTSingningKey.
func (mr *MockAppParametersMockRecorder) GetJWTSingningKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWTSingningKey", reflect.TypeOf((*MockAppParameters)(nil).GetJWTSingningKey))
}

// Init mocks base method.
func (m *MockAppParameters) Init(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockAppParametersMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAppParameters)(nil).Init), arg0)
}
